# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/EricProjects/Grote/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 755)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Dish_Icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Driver = QtWidgets.QWidget()
        self.Tab_Driver.setObjectName("Tab_Driver")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Tab_Driver)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.driver = DriverSelector(self.Tab_Driver)
        self.driver.setMinimumSize(QtCore.QSize(100, 100))
        self.driver.setObjectName("driver")
        self.horizontalLayout_4.addWidget(self.driver)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Tab_Driver, "")
        self.Tab_Scan = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_Scan.sizePolicy().hasHeightForWidth())
        self.Tab_Scan.setSizePolicy(sizePolicy)
        self.Tab_Scan.setObjectName("Tab_Scan")
        self.gridLayout = QtWidgets.QGridLayout(self.Tab_Scan)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scanner = Scanner_Selector(self.Tab_Scan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanner.sizePolicy().hasHeightForWidth())
        self.scanner.setSizePolicy(sizePolicy)
        self.scanner.setObjectName("scanner")
        self.horizontalLayout_3.addWidget(self.scanner, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Tab_Scan, "")
        self.Tab_Analyze = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_Analyze.sizePolicy().hasHeightForWidth())
        self.Tab_Analyze.setSizePolicy(sizePolicy)
        self.Tab_Analyze.setObjectName("Tab_Analyze")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Tab_Analyze)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DataDisplay = ImageView(self.Tab_Analyze)
        self.DataDisplay.setObjectName("DataDisplay")
        self.horizontalLayout_2.addWidget(self.DataDisplay)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.Tab_Analyze, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 414, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImport_CSV = QtWidgets.QAction(MainWindow)
        self.actionImport_CSV.setObjectName("actionImport_CSV")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionImport_CSV_Convert_dBm_to_mW = QtWidgets.QAction(MainWindow)
        self.actionImport_CSV_Convert_dBm_to_mW.setObjectName("actionImport_CSV_Convert_dBm_to_mW")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionImport_CSV)
        self.menuFile.addAction(self.actionImport_CSV_Convert_dBm_to_mW)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grote"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Driver), _translate("MainWindow", "Driver"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Scan), _translate("MainWindow", "Scanner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Analyze), _translate("MainWindow", "Analyze"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionImport_CSV.setText(_translate("MainWindow", "&Import CSV"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionImport_CSV_Convert_dBm_to_mW.setText(_translate("MainWindow", "Import CSV (Convert dBm to mW)"))
        self.actionLoad.setText(_translate("MainWindow", "&Load"))
from Drivers.DriverSelector import DriverSelector
from Scanners.Scanner_Selector import Scanner_Selector
from pyqtgraph import ImageView
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
