# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/EricProjects/Grote/Drivers/ScannerComport.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScannerComport(object):
    def setupUi(self, ScannerComport):
        ScannerComport.setObjectName("ScannerComport")
        ScannerComport.resize(218, 157)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScannerComport.sizePolicy().hasHeightForWidth())
        ScannerComport.setSizePolicy(sizePolicy)
        ScannerComport.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(ScannerComport)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(ScannerComport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_Hider = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Hider.sizePolicy().hasHeightForWidth())
        self.groupBox_Hider.setSizePolicy(sizePolicy)
        self.groupBox_Hider.setTitle("")
        self.groupBox_Hider.setObjectName("groupBox_Hider")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Hider)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_Settings = QtWidgets.QFormLayout()
        self.formLayout_Settings.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_Settings.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_Settings.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_Settings.setObjectName("formLayout_Settings")
        self.label = QtWidgets.QLabel(self.groupBox_Hider)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout_Settings.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_SerialPort = QtWidgets.QComboBox(self.groupBox_Hider)
        self.comboBox_SerialPort.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SerialPort.sizePolicy().hasHeightForWidth())
        self.comboBox_SerialPort.setSizePolicy(sizePolicy)
        self.comboBox_SerialPort.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_SerialPort.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_SerialPort.setObjectName("comboBox_SerialPort")
        self.comboBox_SerialPort.addItem("")
        self.formLayout_Settings.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_SerialPort)
        self.label_2 = QtWidgets.QLabel(self.groupBox_Hider)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout_Settings.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_BaudRate = QtWidgets.QComboBox(self.groupBox_Hider)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_BaudRate.sizePolicy().hasHeightForWidth())
        self.comboBox_BaudRate.setSizePolicy(sizePolicy)
        self.comboBox_BaudRate.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_BaudRate.setObjectName("comboBox_BaudRate")
        self.comboBox_BaudRate.addItem("")
        self.formLayout_Settings.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_BaudRate)
        self.verticalLayout.addLayout(self.formLayout_Settings)
        self.gridLayout_2.addWidget(self.groupBox_Hider, 2, 0, 1, 2)
        self.radioButtonExpand = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonExpand.sizePolicy().hasHeightForWidth())
        self.radioButtonExpand.setSizePolicy(sizePolicy)
        self.radioButtonExpand.setObjectName("radioButtonExpand")
        self.gridLayout_2.addWidget(self.radioButtonExpand, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)

        self.retranslateUi(ScannerComport)
        QtCore.QMetaObject.connectSlotsByName(ScannerComport)

    def retranslateUi(self, ScannerComport):
        _translate = QtCore.QCoreApplication.translate
        ScannerComport.setWindowTitle(_translate("ScannerComport", "Form"))
        self.label.setText(_translate("ScannerComport", "Port"))
        self.comboBox_SerialPort.setItemText(0, _translate("ScannerComport", "-"))
        self.label_2.setText(_translate("ScannerComport", "Baud Rate"))
        self.comboBox_BaudRate.setItemText(0, _translate("ScannerComport", "-"))
        self.radioButtonExpand.setText(_translate("ScannerComport", "Serial Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScannerComport = QtWidgets.QWidget()
    ui = Ui_ScannerComport()
    ui.setupUi(ScannerComport)
    ScannerComport.show()
    sys.exit(app.exec_())

