# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/EricProjects/Grote/Scanners/Display_SSI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Display_SSI(object):
    def setupUi(self, Display_SSI):
        Display_SSI.setObjectName("Display_SSI")
        Display_SSI.resize(275, 304)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Display_SSI.sizePolicy().hasHeightForWidth())
        Display_SSI.setSizePolicy(sizePolicy)
        Display_SSI.setMinimumSize(QtCore.QSize(275, 304))
        self.gridLayout_2 = QtWidgets.QGridLayout(Display_SSI)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Display_SSI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonRun = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRun.sizePolicy().hasHeightForWidth())
        self.buttonRun.setSizePolicy(sizePolicy)
        self.buttonRun.setObjectName("buttonRun")
        self.gridLayout.addWidget(self.buttonRun, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 2)
        self.spinBox_Averaging = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_Averaging.setMinimum(1)
        self.spinBox_Averaging.setObjectName("spinBox_Averaging")
        self.gridLayout.addWidget(self.spinBox_Averaging, 4, 1, 1, 1)
        self.buttonStop = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStop.sizePolicy().hasHeightForWidth())
        self.buttonStop.setSizePolicy(sizePolicy)
        self.buttonStop.setObjectName("buttonStop")
        self.gridLayout.addWidget(self.buttonStop, 5, 1, 1, 1)
        self.Polarisation = QtWidgets.QComboBox(self.groupBox)
        self.Polarisation.setObjectName("Polarisation")
        self.gridLayout.addWidget(self.Polarisation, 1, 1, 1, 1)
        self.SamplingRate = QtWidgets.QComboBox(self.groupBox)
        self.SamplingRate.setObjectName("SamplingRate")
        self.gridLayout.addWidget(self.SamplingRate, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_SSI = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SSI.sizePolicy().hasHeightForWidth())
        self.label_SSI.setSizePolicy(sizePolicy)
        self.label_SSI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_SSI.setObjectName("label_SSI")
        self.gridLayout.addWidget(self.label_SSI, 7, 0, 1, 2)
        self.Band = QtWidgets.QComboBox(self.groupBox)
        self.Band.setObjectName("Band")
        self.gridLayout.addWidget(self.Band, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Display_SSI)
        QtCore.QMetaObject.connectSlotsByName(Display_SSI)

    def retranslateUi(self, Display_SSI):
        _translate = QtCore.QCoreApplication.translate
        Display_SSI.setWindowTitle(_translate("Display_SSI", "Form"))
        self.groupBox.setTitle(_translate("Display_SSI", "Signal Strength Indicator"))
        self.buttonRun.setText(_translate("Display_SSI", "Run"))
        self.label_5.setText(_translate("Display_SSI", "Sampling rate"))
        self.label_4.setText(_translate("Display_SSI", "Averaging"))
        self.label_2.setText(_translate("Display_SSI", "Signal Strength"))
        self.buttonStop.setText(_translate("Display_SSI", "Stop"))
        self.label_3.setText(_translate("Display_SSI", "Band"))
        self.label_SSI.setText(_translate("Display_SSI", "0.0"))
        self.label.setText(_translate("Display_SSI", "Polarisation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Display_SSI = QtWidgets.QWidget()
    ui = Ui_Display_SSI()
    ui.setupUi(Display_SSI)
    Display_SSI.show()
    sys.exit(app.exec_())
